FROM node:20-alpine
LABEL version="1.0.3"
LABEL build_id="36002e78"

WORKDIR /app

COPY package*.json ./
RUN npm ci

COPY . .

ARG VITE_SUPABASE_URL
ARG VITE_SUPABASE_ANON_KEY
ENV VITE_SUPABASE_URL=$VITE_SUPABASE_URL
ENV VITE_SUPABASE_ANON_KEY=$VITE_SUPABASE_ANON_KEY

RUN npm run build

ENV NODE_ENV=production
ENV PORT=3030

EXPOSE 3030

CMD ["npm", "start"]
