/**
 * Evolution API client — talks to a self-hosted Evolution server
 * (https://github.com/EvolutionAPI/evolution-api) that wraps Baileys
 * to provide multiple WhatsApp instances per campaign.
 *
 * Configuration (env vars, server-side only — NEVER expose to frontend):
 *   EVOLUTION_API_URL          base URL (e.g. https://evolution.example.com)
 *   EVOLUTION_GLOBAL_API_KEY   global API key (used to create instances)
 *   EVOLUTION_WEBHOOK_URL      public webhook URL we expose to Evolution
 *
 * Per-instance API keys are generated by Evolution and stored encrypted
 * in whatsapp_instances.apiKey — they're only ever used server-side.
 */

const EVOLUTION_API_URL = process.env.EVOLUTION_API_URL?.replace(/\/+$/, '');
const EVOLUTION_GLOBAL_API_KEY = process.env.EVOLUTION_GLOBAL_API_KEY;
const EVOLUTION_WEBHOOK_URL = process.env.EVOLUTION_WEBHOOK_URL?.replace(/\/+$/, '');

export interface EvolutionCreateResult {
  instanceId: string;
  apiKey: string;
  qrCode?: string | null;
}

export interface EvolutionSendResult {
  messageId: string;
}

export type EvolutionStatus = 'pending' | 'qrcode' | 'connected' | 'disconnected';

export function isEvolutionConfigured(): boolean {
  return !!(EVOLUTION_API_URL && EVOLUTION_GLOBAL_API_KEY);
}

async function call<T = unknown>(
  method: 'GET' | 'POST' | 'DELETE',
  path: string,
  body: unknown | undefined,
  apiKey: string,
): Promise<T> {
  if (!EVOLUTION_API_URL) {
    throw new Error('evolution_not_configured');
  }
  const res = await fetch(`${EVOLUTION_API_URL}${path}`, {
    method,
    headers: {
      'Content-Type': 'application/json',
      apikey: apiKey,
    },
    body: body ? JSON.stringify(body) : undefined,
  });
  if (!res.ok) {
    const errText = await res.text().catch(() => '');
    throw new Error(`evolution_${method}_${path}_${res.status}:${errText.slice(0, 200)}`);
  }
  return res.json() as Promise<T>;
}

/**
 * Create a new instance. Returns the per-instance API key (stored encrypted
 * in whatsapp_instances.apiKey) and the initial QR code if available.
 *
 * The instanceName must be globally unique inside the Evolution server.
 * We use `cp_${campaignId}_${slug}` as the convention.
 */
export async function createInstance(instanceName: string): Promise<EvolutionCreateResult> {
  if (!EVOLUTION_GLOBAL_API_KEY) throw new Error('evolution_not_configured');

  const body: Record<string, unknown> = {
    instanceName,
    integration: 'WHATSAPP-BAILEYS',
    qrcode: true,
  };

  if (EVOLUTION_WEBHOOK_URL) {
    body.webhook = {
      url: `${EVOLUTION_WEBHOOK_URL}/evolution/${encodeURIComponent(instanceName)}`,
      byEvents: false,
      base64: false,
      events: ['MESSAGES_UPSERT', 'CONNECTION_UPDATE'],
    };
  }

  // Evolution v2 returns: { instance: { instanceId, ... }, hash: { apikey }, qrcode: { base64 } }
  const result = await call<any>('POST', '/instance/create', body, EVOLUTION_GLOBAL_API_KEY);

  return {
    instanceId: result?.instance?.instanceId ?? instanceName,
    apiKey: result?.hash?.apikey ?? result?.hash ?? '',
    qrCode: result?.qrcode?.base64 ?? null,
  };
}

/**
 * Fetch a fresh QR code for pairing. Used when the user lost the original
 * QR or it expired (Evolution QR codes are valid for ~60 seconds).
 */
export async function getQRCode(instanceName: string, apiKey: string): Promise<{ qrCode: string | null; status: EvolutionStatus }> {
  const result = await call<any>('GET', `/instance/connect/${encodeURIComponent(instanceName)}`, undefined, apiKey);
  // Response shape: { base64, code, pairingCode } or { instance: { state } }
  return {
    qrCode: result?.base64 ?? result?.qrcode?.base64 ?? null,
    status: 'qrcode',
  };
}

/**
 * Poll connection state. 'open' = connected, 'connecting' = waiting QR scan,
 * 'close' = disconnected. We normalize to our internal status enum.
 */
export async function getStatus(instanceName: string, apiKey: string): Promise<EvolutionStatus> {
  try {
    const result = await call<any>('GET', `/instance/connectionState/${encodeURIComponent(instanceName)}`, undefined, apiKey);
    const state = result?.instance?.state ?? result?.state ?? 'unknown';
    if (state === 'open') return 'connected';
    if (state === 'connecting') return 'qrcode';
    return 'disconnected';
  } catch {
    return 'disconnected';
  }
}

/** Send a text message via this instance. `to` should be E.164 without '+'. */
export async function sendText(
  instanceName: string,
  apiKey: string,
  to: string,
  text: string,
): Promise<EvolutionSendResult> {
  const result = await call<any>(
    'POST',
    `/message/sendText/${encodeURIComponent(instanceName)}`,
    { number: to, text },
    apiKey,
  );
  return { messageId: result?.key?.id ?? result?.id ?? '' };
}

/** Permanently delete an instance from the Evolution server. */
export async function deleteInstance(instanceName: string, apiKey: string): Promise<void> {
  try {
    // Logout first to free the WhatsApp session, then delete
    await call('DELETE', `/instance/logout/${encodeURIComponent(instanceName)}`, undefined, apiKey).catch(() => {});
    await call('DELETE', `/instance/delete/${encodeURIComponent(instanceName)}`, undefined, apiKey);
  } catch (err: any) {
    // Surface but don't crash callers — instance may already be gone
    console.warn('[Evolution] delete instance failed:', err.message);
  }
}
