-- Meeting records: agendas, recordings, transcripts, AI analysis
CREATE TABLE IF NOT EXISTS meeting_records (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  "campaignId" text NOT NULL,
  title text NOT NULL DEFAULT 'Reunião de Planejamento',
  agenda jsonb,            -- [{ topic, description }] generated by AI
  "scheduledAt" timestamptz,
  "recordedAt" timestamptz,
  duration int,            -- seconds
  transcript text,
  summary text,
  actions jsonb,           -- [{ title, assignee, dueDate, bucket, approved, agentTaskId }]
  highlights jsonb,        -- [string] — key points flagged by AI
  status text NOT NULL DEFAULT 'draft',  -- draft | transcribed | analyzed
  "createdAt" timestamptz NOT NULL DEFAULT now(),
  "updatedAt" timestamptz NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS meeting_records_campaign_created
  ON meeting_records ("campaignId", "createdAt" DESC);

ALTER TABLE meeting_records ENABLE ROW LEVEL SECURITY;

CREATE POLICY "meeting_records_select_own" ON meeting_records
  FOR SELECT USING ("campaignId" = get_user_campaign_id_text() OR is_supreme_admin());

CREATE POLICY "meeting_records_insert_own" ON meeting_records
  FOR INSERT WITH CHECK ("campaignId" = get_user_campaign_id_text() OR is_supreme_admin());

CREATE POLICY "meeting_records_update_own" ON meeting_records
  FOR UPDATE USING ("campaignId" = get_user_campaign_id_text() OR is_supreme_admin());

CREATE POLICY "meeting_records_delete_own" ON meeting_records
  FOR DELETE USING ("campaignId" = get_user_campaign_id_text() OR is_supreme_admin());

CREATE POLICY "meeting_records_service_role" ON meeting_records
  FOR ALL USING (auth.role() = 'service_role');

-- Add meetings feature to Pro and Enterprise plans
UPDATE plans
SET features = array_append(features, 'meetings')
WHERE name IN ('Pro', 'Enterprise')
  AND NOT ('meetings' = ANY(features));

-- Backfill active subscriptions so existing users get access
UPDATE subscriptions s
SET features = array_append(s.features, 'meetings')
FROM plans p
WHERE s."planId" = p.id
  AND s.status = 'active'
  AND p.name IN ('Pro', 'Enterprise')
  AND NOT ('meetings' = ANY(s.features));
